all:q1 q2 q3 q4 q5 q6

q1:questionOne.exe
	./questionOne

questionOne.exe:questionOne.cpp
	g++ questionOne.cpp -o questionOne

q2: questionTwo.exe
	./questionTwo

questionTwo.exe:questionTwo.cpp
	g++ questionTwo.cpp -o questionTwo

q3:questionThree.exe
	./questionThree

questionThree.exe:questionThree.cpp
	g++ questionThree.cpp -o questionThree

q4:questionFour.exe
	./questionFour

questionFour.exe:questionFour.cpp
	g++ questionFour.cpp -o questionFour

q5:questionFive.exe
	./questionFive

questionFive.exe:questionFive.cpp
	g++ questionFive.cpp -o questionFive

q6:questionSix.exe
	./questionSix

questionSix.exe:questionSix.cpp
	g++ questionSix.cpp -o questionSix
clean:
	rm -f questionTwo
	rm -f questionOne
	rm -f questionThree
	rm -f questionFour
	rm -f questionFive
	rm -f questionSix
